name: Deploy Infrastructure

on:
  pull_request:
    inputs:
      TF_ENVIRONMENT:
        description: Terraform environment 
        required: true
  workflow_dispatch:
    inputs:
      TF_ENVIRONMENT:
        description: Terraform environment
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy-infrastructure:
    uses: madnansystems87/reusable-templates/.github/workflows/infrastructure-provisioning.yml@main
    with:
      TF_ENVIRONMENT: ${{ github.event.inputs.TF_ENVIRONMENT }}
      ROLE_NAME: github-actions-oidc-role
    secrets:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_AWS_REGION: ${{ secrets.S3_AWS_REGION }}
      TF_STATE_S3_BUCKET: ${{ secrets.TF_STATE_S3_BUCKET }}
      TF_STATE_FILE_KEY: ${{ secrets.TF_STATE_FILE_KEY }}
      TF_STATE_DYNAMODB_TABLE: ${{ secrets.TF_STATE_DYNAMODB_TABLE }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}